<a href="https://colab.research.google.com/github/LucianoBV/Procesamiento-del-habla/blob/main/%C3%9Altimo_desaf%C3%ADo_NPL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DESAFÍO OBLIGATORIO FINAL MARTÍN FIERRO

**ALUMNO:** Vargas luciano Benjamín

**TEMA:** Clasificación

#TEMA 2 CLASIFICACIÓN
 Determinar si un verso (o estrofa) es del Martín Fierro o del Fausto (Estanislao Lopez)

In [ ]:
import numpy as np
import string
from sklearn.model_selection import train_test_split

#Preparación de los datos:
Se cargan los textos de ambas obras y se les asigna una etiqueta: 1 para Martín Fierro y 0 para Fausto.
Se preprocesan los textos convirtiéndolos a minúsculas y eliminando la puntuación.
Se divide el conjunto de datos en entrenamiento (80%) y prueba (20%).

In [ ]:
archivos = ['FAUSTO-Estanislado_del_Campo.txt', "el_gaucho_martin_fierro.txt"
]

In [ ]:
textos = []
etiquetas = []

In [ ]:
for etiqueta, f in enumerate(archivos):
    print(f"{f} Corresponde a {etiqueta}")

FAUSTO-Estanislado_del_Campo.txt Corresponde a 0
el_gaucho_martin_fierro.txt Corresponde a 1


In [ ]:
for etiqueta, f in enumerate(archivos):

    with open(f, 'r', encoding='utf-8') as archivo:
        for line in archivo:
            print(line)
            # pasamos a minuscula
            line = line.rstrip().lower()
            print(line)
            if line:
                # eliminamos puntuación
                line = line.translate(str.maketrans('', '', string.punctuation))
                textos.append(line)
                etiquetas.append(etiqueta)
            print(line)


Se truncaron las últimas líneas 5000 del resultado de transmisión.
 ya soy jaca vieja hermano
 Con las púas como anzuelo,

 con las púas como anzuelo,
 con las púas como anzuelo
 Y á quien va le niega el suelo

 y á quien va le niega el suelo
 y á quien va le niega el suelo
 Hasta el mas remoto grano.

 hasta el mas remoto grano.
 hasta el mas remoto grano
 Se apió el Pollo y se pegaron

 se apió el pollo y se pegaron
 se apió el pollo y se pegaron
 Tal abrazo con Laguna,

 tal abrazo con laguna,
 tal abrazo con laguna
 Que sus dos almas en una

 que sus dos almas en una
 que sus dos almas en una
 Acaso se misturaron.

 acaso se misturaron.
 acaso se misturaron
 Cuando se desenredaron,

 cuando se desenredaron,
 cuando se desenredaron
Despues de haber lagrimiao,

despues de haber lagrimiao,
despues de haber lagrimiao
 El overito rosao

 el overito rosao
 el overito rosao
 Una oreja se rascaba,

 una oreja se rascaba,
 una oreja se rascaba
 Visto que la refregaba

 visto que la refregab

In [ ]:
textos

['fausto',
 ' impresiones del gaucho anastasio el pollo en la',
 ' representación de esta opera',
 'estanislao del campo',
 'al poeta ricardo gutierrez',
 ' diálogo entre dos gauchos anastasio y don laguna donde se intercambian impresiones',
 ' sobre la ópera fausto vista en el teatro colón preciosa pieza humorística que mereció',
 ' elogios de josé hernández jorge luis borges y mujica laínez entre otros',
 'índice de contenido',
 ' carta de juan carlos gómez3',
 ' respuesta de estanislao del campo7',
 ' carta de ricardo gutiérrez8',
 ' carta de carlos guido y spano11– i – 13–  ii – 19– iii – 27– iv – 33– v – 43– vi –  51',
 'carta de juan carlos gómez',
 ' del campo',
 'las buenas obras son siempre hijas de los bellos sentimientos porque las mejores',
 ' y mas grandes ideas nacen en el corazon llevando consigo la emocion de que',
 ' nacieron',
 'su pobreza de poeta empeñada en aliviar dolorosos infortunios ha apelado á',
 ' esa infaligable alquimista de la imajinacion que elabora los 

In [ ]:
print(etiquetas)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
# Se divide el conjunto de datos en entrenamiento (50%) y prueba (50%).
train_text, test_text, Ytrain, Ytest = train_test_split(textos, etiquetas, test_size=0.5, random_state=42)

In [ ]:
len(Ytrain), len(Ytest)

(823, 823)

#Construcción del vocabulario:
Se crea un diccionario que asigna un índice único a cada palabra en el vocabulario, incluyendo una entrada especial para palabras desconocidas

In [ ]:
#"<unk>" es una convención que se utiliza en el procesamiento de lenguaje natural para representar palabras
# desconocidas o fuera del vocabulario. En este caso, se está asignando el índice 0 a esta palabra especial.
indice = 1
indicepalabras = {'<unk>': 0}

In [ ]:
indicepalabras

{'<unk>': 0}

In [ ]:
#Construcción de un Diccionario de Codificación de Palabras a Índices
for texto in train_text:
    tokens = texto.split()
    for token in tokens:
        if token not in indicepalabras:
            indicepalabras[token] = indice
            indice += 1

In [ ]:
len(indicepalabras)

1815

In [ ]:
# convert datos en enteros
train_text_int = []
test_text_int = []

In [ ]:
for texto in train_text:
    tokens = texto.split()
    linea_entero = [indicepalabras[token] for token in tokens]
    train_text_int.append(linea_entero)

In [ ]:
train_text_int

[[1, 2, 3],
 [4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13],
 [14, 6, 15, 16, 12, 17],
 [6, 18, 19, 20, 21],
 [22, 2, 23, 24, 25],
 [26, 27, 28, 29, 12, 30],
 [31, 32, 33, 34],
 [14, 35, 6, 36, 37, 38],
 [12, 39, 40, 41, 42],
 [43, 26, 8, 44],
 [14, 45, 46, 47, 48, 49],
 [50, 51, 52, 53],
 [54, 55, 52, 40, 49, 52, 56],
 [57, 58, 59, 60, 61, 62, 63, 64, 2, 65, 60, 2, 66, 8],
 [67, 68, 52, 58, 8, 69],
 [36, 70, 6, 71, 72],
 [40, 73, 74, 45, 60, 71, 75, 11, 60, 71, 76, 14, 77, 78, 45, 79],
 [80, 58, 81, 82, 83],
 [84, 45, 85, 86, 52, 87],
 [8, 88, 89, 90],
 [14, 6, 12, 91, 92],
 [8, 93, 60, 36, 19, 8, 2, 94],
 [47, 71, 95, 14, 96],
 [97, 98, 14, 99, 100, 101, 102, 103, 104],
 [105, 106, 107, 18, 108],
 [41, 109, 110],
 [79, 111],
 [110, 36, 5, 112],
 [12, 113, 8, 71, 114, 115, 107, 116, 6, 117, 118, 14, 119, 6],
 [120, 40, 52, 121, 122],
 [47, 12, 123, 124, 8, 125, 47, 36, 126, 127, 8, 128, 52, 129, 130],
 [40, 52, 45, 131, 132, 133, 134, 135, 107, 136, 12, 76, 137, 6],
 [68, 52, 138, 139],
 [12, 

In [ ]:
for texto in test_text:
    tokens = texto.split()
    line_as_int = [indicepalabras.get(token, 0) for token in tokens]
    test_text_int.append(line_as_int)

In [ ]:
test_text_int

[[12, 39, 1139, 60, 1267],
 [1522, 0, 0, 647],
 [22, 744, 745, 2, 0],
 [861, 60, 36, 354],
 [644, 813, 0, 524, 736],
 [86, 0, 52, 0, 0, 225, 12, 0],
 [258, 616, 1036, 112],
 [0, 0, 14, 0],
 [45, 58, 866, 55, 0],
 [14, 79, 0, 27, 0],
 [52, 371, 386, 86, 52, 909],
 [0, 20, 0],
 [0, 961, 79, 239],
 [2, 555, 0],
 [14, 26, 1707, 12, 0],
 [71, 818, 0, 0],
 [439, 57, 0],
 [1400, 1718, 45, 650, 1028],
 [1441, 753, 0, 191],
 [800, 36, 0, 0],
 [12, 529, 8, 18, 156],
 [258, 0, 116, 0],
 [120, 0, 6, 36, 0],
 [902, 12, 349, 173],
 [14, 8, 0, 0, 428],
 [0, 0, 743, 0],
 [14, 0, 8, 0],
 [253, 41, 370, 0],
 [52, 12, 76, 86, 0],
 [0, 12, 1572, 8, 71, 469],
 [150, 1161, 8, 717, 0],
 [1521, 500, 169, 71, 0],
 [36, 0, 79, 561, 382],
 [20, 619, 1789, 0],
 [1377, 0, 0],
 [0, 0],
 [258, 60, 71, 0, 1250],
 [36, 1107, 52, 36, 0],
 [12, 0, 172, 0, 58, 0, 79, 0, 0, 0, 60, 36, 5, 125],
 [52, 1337, 60, 0, 8, 440],
 [1193, 123, 0, 169, 0, 717, 86, 0, 240, 52, 606, 60],
 [0, 257, 14, 2, 1459],
 [150, 36, 0, 707, 0],


In [ ]:
# Inicializar matrices de transición y probabilidades iniciales
V = len(indicepalabras)
A0 = np.ones((V, V))
pi0 = np.ones(V)

A1 = np.ones((V, V))
pi1 = np.ones(V)

In [ ]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [ ]:
pi0

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
# La función compute_counts actualiza las matrices A y pi con las cuentas de las transiciones entre palabras y las frecuencias de las palabras iniciales para cada clase.
def compute_counts(text_as_int, A, pi):
    for tokens in text_as_int:
        last_idx = None
        for idx in tokens:
            # estamos en la primera palabra de la secuencia
            if last_idx is None:
                pi[idx] += 1
            else:
                A[last_idx, idx] += 1
            last_idx = idx

compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], A1, pi1)

In [ ]:
pi0

array([1., 2., 4., ..., 1., 1., 1.])

In [ ]:
pi1

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
pi1

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 2., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [ ]:
# Se normalizan A0, pi0, A1 y pi1 para que representen probabilidades válidas (sumando a 1).
A0 /= A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [ ]:
pi0

array([0.00037951, 0.00075901, 0.00151803, ..., 0.00037951, 0.00037951,
       0.00037951])

In [ ]:
A0

array([[0.00055096, 0.00055096, 0.00055096, ..., 0.00055096, 0.00055096,
        0.00055096],
       [0.00055066, 0.00055066, 0.00110132, ..., 0.00055066, 0.00055066,
        0.00055066],
       [0.00052938, 0.00052938, 0.00052938, ..., 0.00052938, 0.00052938,
        0.00052938],
       ...,
       [0.00055066, 0.00055066, 0.00110132, ..., 0.00055066, 0.00055066,
        0.00055066],
       [0.00055096, 0.00055096, 0.00055096, ..., 0.00055096, 0.00055096,
        0.00055096],
       [0.00055066, 0.00055066, 0.00055066, ..., 0.00055066, 0.00055066,
        0.00055066]])

In [ ]:
# Calcula el logaritmo de A y pi, ya que no necesitamos las probabilidades reales
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [ ]:
logpi0

array([-7.87663846, -7.18349128, -6.4903441 , ..., -7.87663846,
       -7.87663846, -7.87663846])

In [ ]:
logA0

array([[-7.50384075, -7.50384075, -7.50384075, ..., -7.50384075,
        -7.50384075, -7.50384075],
       [-7.50439156, -7.50439156, -6.81124438, ..., -7.50439156,
        -7.50439156, -7.50439156],
       [-7.54380287, -7.54380287, -7.54380287, ..., -7.54380287,
        -7.54380287, -7.54380287],
       ...,
       [-7.50439156, -7.50439156, -6.81124438, ..., -7.50439156,
        -7.50439156, -7.50439156],
       [-7.50384075, -7.50384075, -7.50384075, ..., -7.50384075,
        -7.50384075, -7.50384075],
       [-7.50439156, -7.50439156, -7.50439156, ..., -7.50439156,
        -7.50439156, -7.50439156]])

In [ ]:
# Se calculan las probabilidades a priori p0 y p1 para cada clase basándose en la frecuencia de cada clase en los datos de entrenamiento.
count0 = sum(y == 0 for y in Ytrain)  # Cuenta de etiquetas de clase 0 en Ytrain
count1 = sum(y == 1 for y in Ytrain)  # Cuenta de etiquetas de clase 1 en Ytrain
total = len(Ytrain)  # Cantidad total de ejemplos de entrenamiento
p0 = count0 / total  # Probabilidad a priori de clase 0
p1 = count1 / total  # Probabilidad a priori de clase 1
logp0 = np.log(p0)  # Logaritmo de la probabilidad a priori de clase 0
logp1 = np.log(p1)  # Logaritmo de la probabilidad a priori de clase 1
p0, p1  # Imprime las probabilidades a priori de ambas clases


(0.9963547995139733, 0.0036452004860267314)

#Clasificación:
Se crea una instancia de la clase Classifier con las matrices de transición, las probabilidades iniciales y las probabilidades a priori calculadas en el paso anterior.
Se utiliza el método predict del clasificador para predecir la clase de un verso o estrofa dado.

In [ ]:
# contrucción de un clasificador
class Classifier:
    def __init__(self, logAs, logpis, logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.K = len(logpriors) # número de clases

    def _compute_log_likelihood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]

        last_idx = None
        logprob = 0
        for idx in input_:
            if last_idx is None:
                # Es el primer token en la secuencia
                logprob += logpi[idx]
            else:
                # Calcula la probabilidad de transición de la palabra anterior a la actual
                logprob += logA[last_idx, idx]

            # Actualiza last_idx para la próxima iteración
            last_idx = idx

        return logprob

    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        for i, input_ in enumerate(inputs):
            # Calcula los logaritmos de las probabilidades posteriores para cada clase
            posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] \
                          for c in range(self.K)]
            # Elige la clase con la mayor probabilidad posterior como la predicción
            pred = np.argmax(posteriors)
            predictions[i] = pred
        return predictions

In [ ]:
# Cada arreglo debe estar en orden ya que se asume que las clases indexan estas listas
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

#Predecir y evaluar:

Se utiliza el método predict del clasificador para predecir la clase de los versos en los conjuntos de entrenamiento y prueba.
Se calcula la precisión del clasificador en ambos conjuntos comparando las predicciones con las etiquetas reales.

In [ ]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

Train acc: 0.9975698663426489


In [ ]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

Test acc: 0.9975698663426489
